sudo: required
language: cpp
dist: bionic
before_script:
- echo "deb http://archive.ubuntu.com/ubuntu xenial main universe" | sudo tee -a /etc/apt/sources.list
- sudo apt-get update -qq
- sudo scripts/gtest_install_script.sh
script:
- conan install .
- cmake .
- cmake --build .
- cmake --build . --target test
- cmake --build . --target package
deploy:
  provider: script
  skip_cleanup: true
  on:
    all_branches: true
  script:
  - curl -T allocator-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb -umakerslet:$BINTRAY_API_KEY "https://api.bintray.com/content/makerslet/allocator/package/$TRAVIS_BUILD_NUMBER/allocator-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb;deb_distribution=trusty;deb_component=main;deb_architecture=amd64;publish=1"
